branch-defaults:
  awsdeploy:
    environment: mb-dev
    group_suffix: null
global:
  application_name: mbnode-docker
  default_ec2_keyname: hopscotchdev
  default_platform: Docker 1.9.1
  default_region: us-west-2
  profile: null
  sc: git
